AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.2

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/DotPosition:
  EnforcedStyle: leading

Style/Encoding:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$statsd, $rollout, $rails_rake_task]

Style/FileName:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Lint/AssignmentInCondition:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Rails:
  Enabled: true

Rails/ActionFilter:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: false
